apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'unithon'
    server: 'https://kubernetes.default.svc'
  source:
    path: app/backend-dev
    repoURL: 'https://github.com/Unithon-10th-team8/devops'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
