apiVersion: apps/v1
kind: Deployment
metadata:
  name: unithon-backend-main
  namespace: unithon
  labels:
    app: unithon-backend-main
spec:
  selector:
    matchLabels:
      app: unithon-backend-main
  template:
    metadata:
      labels:
        app: unithon-backend-main
    spec:
      initContainers:
        - name: unithon-backend-dev-init
          image: hyeonwoo5342/unithon-backend-main:4
          imagePullPolicy: Always
          command: [ 'sh', '-c', '/app/.venv/bin/python manage.py migrate' ]
          envFrom:
            - secretRef:
                name: unithon-backend-dev-secret
          resources:
            requests:
              memory: '200Mi'
              cpu: '150m'
            limits:
              memory: '200Mi'
              cpu: '150m'
      containers:
        - name: unithon-backend-main
          image: hyeonwoo5342/unithon-backend-main:4
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: '200Mi'
              cpu: '150m'
            limits:
              memory: '200Mi'
              cpu: '150m'
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: unithon-backend-main-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: unithon-backend-main
  namespace: unithon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unithon-backend-main
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: unithon-backend-main
  namespace: unithon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: unithon-backend-main
